# Generated by Django 4.2.3 on 2023-07-14 16:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduce',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='disc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
