# Generated by Django 4.2.3 on 2023-07-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
