# Generated by Django 4.2.3 on 2023-07-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0002_category_slug_posts_slug_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='field',
        ),
    ]
