# Generated by Django 4.2.3 on 2023-07-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0003_posts_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='fileUpload/%Y/%m'),
        ),
    ]
